apiVersion: v1
kind: Pod
metadata: 
  name: labels
  namespace: roboshop
  labels:
    course: DevOps
    Trainer: "Siva"
spec:
  containers:
  - name: nginx1
    image: nginx
    ports:
    - containerPort: 80
    