apiVersion: v1
kind: Pod
metadata:
  name: hi
  annotations:
    environment: "production"
    app-version: "1.0"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
